# Generated by Django 5.1.2 on 2024-10-31 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date_of_purchase',
            new_name='date_of_bill',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='price_per_unit',
            new_name='net_total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_including_gst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='units_purchased',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_purchased', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_including_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.bill')),
            ],
        ),
    ]
