# Generated by Django 5.1.2 on 2024-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_rename_date_of_purchase_bill_date_of_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bill',
            new_name='bill_number',
        ),
    ]
