# Generated by Django 5.1.2 on 2024-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_rename_bill_number_item_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units_purchased',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
